// <auto-generated />
using System;
using ExtendCorrales.Models.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ExtendCorrales.Migrations
{
    [DbContext(typeof(ExtendCorralesDBContext))]
    partial class ExtendCorralesDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ExtendCorrales.Models.ExtendCorral", b =>
                {
                    b.Property<int>("ExtendCorralId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Categoria");

                    b.Property<string>("Condicion");

                    b.Property<int>("Corral");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Edad");

                    b.Property<string>("EstadoGeneral");

                    b.Property<DateTime>("FechaLlegada");

                    b.Property<string>("HoraLlegada");

                    b.Property<int>("NroTropa");

                    b.Property<string>("PesoGeneral");

                    b.Property<string>("Raza");

                    b.Property<int>("TropaId");

                    b.Property<DateTime>("Updated");

                    b.HasKey("ExtendCorralId");

                    b.ToTable("ExtendCorral");
                });
#pragma warning restore 612, 618
        }
    }
}
